_wandb:
    value:
        cli_version: 0.21.0
        e:
            6z8phqdisztaybpvnqu4i518uyr8ajc2:
                codePath: train.ipynb
                codePathLocal: train.ipynb
                cpu_count: 14
                cpu_count_logical: 20
                disk:
                    /:
                        total: "783444602880"
                        used: "243927347200"
                email: mangadoddis_ug_22@cse.nits.ac.in
                executable: C:\Program Files\Python312\python.exe
                host: Srikar_Device
                memory:
                    total: "16876888064"
                os: Windows-11-10.0.26100-SP0
                program: train.ipynb
                python: CPython 3.12.4
                root: D:\Daily Practice\Transformers
                startedAt: "2025-07-11T11:15:09.093684Z"
                writerId: 6z8phqdisztaybpvnqu4i518uyr8ajc2
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 5
                - 11
                - 40
                - 41
                - 49
                - 51
                - 53
                - 105
            "2":
                - 1
                - 5
                - 11
                - 40
                - 41
                - 49
                - 51
                - 53
                - 105
            "3":
                - 2
                - 16
            "4": 3.12.4
            "5": 0.21.0
            "6": 4.51.3
            "8":
                - 1
                - 3
            "12": 0.21.0
            "13": windows-amd64
batch_size:
    value: 8
d_model:
    value: 512
datasource:
    value: csv
experiment_name:
    value: runs/transformer_model
lang_src:
    value: english
lang_tgt:
    value: telugu
lr:
    value: 0.0001
model_basename:
    value: transformer_model_
model_folder:
    value: weights
num_epochs:
    value: 30
preload:
    value: latest
seq_len:
    value: 350
tokenizer_file:
    value: tokenizer_{0}.json
